apiVersion: v1
kind: ConfigMap
metadata:
  name: tradepulse-grafana-datasource
  namespace: tradepulse
data:
  datasource.yml: |
    apiVersion: 1

    datasources:
      - name: Prometheus
        uid: prometheus
        type: prometheus
        access: proxy
        url: http://tradepulse-prometheus:9090
        isDefault: true
        editable: true