apiVersion: v1
kind: ConfigMap
metadata:
  name: tradepulse-prometheus-config
  namespace: tradepulse
data:
  prometheus.yml: |
    global:
      scrape_interval: 5s

    scrape_configs:
      - job_name: "tradepulse-api-k8s"
        metrics_path: "/metrics"
        static_configs:
          - targets: ["tradepulse-api:8000"]